<?php return array (
  'btn' => '#0ca3d1',
  'btn_text' => '#ffffff',
  'bg_page' => '#e3e3e3',
  'text_top' => '#000000',
  'link_top' => '#2dc4f0',
  'bg_top' => '#dbdbdb',
  'text_head' => '#ffffff',
  'link_head' => '#2dc4f0',
  'bg_header' => '#ffffff',
  'text' => '#444444',
  'link' => '#2dc4f0',
  'bg_body' => '#ffffff',
  'text_foot' => '#444444',
  'link_foot' => '#2dc4f0',
  'bg_footer' => '#d1d1d1',
  'text_bottom' => '#444444',
  'link_bottom' => '#2dc4f0',
  'bg_bottom' => '',
);